    <p class="has-text-align-center">AVISO LEGAL Y TÉRMINOS Y CONDICIONES GENERALES DE USO DEL SITIO WEB</p>
    <p class="has-text-align-center">www.rosistirem.com</p>
    <p><strong>I. Titular del sitio Web</strong></p>
    <p>En cumplimiento con el deber de información dispuesto en la Ley 34/2002 de Servicios de la Sociedad de la Información y el Comercio Electrónico (LSSI-CE) de 11 de julio, se facilitan a continuación los siguientes datos de información general de este sitio web:</p>
    <p>Este sitio web, <a href="http://www.rosistirem.com">www.rosistirem.com</a>, es propiedad de ROSISTIREM, S.L. provista de CIF número B-67622241 con domicilio en C/ Rull, 3 08002 Barcelona y constituida por tiempo indefinido en fecha 15 de mayo de 2020 mediante escritura pública autorizada por la Notario de Barcelona Doña Sonia Dalmases Mahamud, bajo el número 250 de su protocolo, inscrita en el Registro Mercantil de Barcelona al tomo 47310, folio 53, hoja número 489628.</p>
    <p>Para contactar con nosotros puedes utilizar la dirección de correo electrónico <a href="mailto:rosistirem@gmail.com">rosistirem@gmail.com</a> o en el numero de teléfono 93.199.71.99.</p>
    <p><br><strong>II. Uso del Contenido del Sitio Web / Propiedad Intelectual e Industrial</strong></p>
    <p><span style="text-decoration: underline;">Información sobre Copyright</span></p>
    <p>Copyright © 2022 Rosistirem</p>
    <p><span style="text-decoration: underline;">Marcas</span></p>
    <p>El logo de Rosistirem y todos sus slogans publicitarios son marcas de Rosistirem, que posee también sus copyrights. Están prohibidos la reproducción o distribución de las marcas, software, copyrights y/o el contenido, total o parcial, de su web sin nuestra autorización.</p>
    <p><span style="text-decoration: underline;">Uso del Contenido del Sitio Web</span></p>
    <p>El contenido incluido en este sitio web puede ser utilizado solo para uso personal, informativo y/o sin fines comerciales y no puede ser modificado o alterado bajo ninguna forma y/o circunstancia. No podrás usar, publicar, dar licencia, enviar, descargar, copiar, imprimir, exhibir, interpretar, reproducir transmitir o distribuir ninguna información de este sitio web sin la previa autorización de Rosistirem. Pero el usuario podrá crear enlaces al Sitio Web para el uso privado y no comercial sujeto a las siguientes condiciones, reservándose ROSISTIREM el derecho a solicitar, en cualquier momento, la eliminación inmediata de cualquier enlace al sitio web:<br> -Será un derecho revocable y no exclusivo.<br> -No podrá dar a entender que ROSISTIREM recomienda dicho sitio web,  servicios o productos ni falsear su relación.<br> -No debe incluir contenidos considerados de mal gusto, obscenos,  ofensivos controvertidos, incitadores a la violencia o discriminación por  sexo, raza o religión, contrarios al orden público o ilícito.<br> -El enlace debe dirigir al Sitio Web, sin que se permita la reproducción  como parte de su web o dentro de uno de sus frames o crear un browser  sobre cualquiera de las páginas del sitio web.</p>
    <p>ROSISTIREM no puede controlar la información, contenidos, productos o servicios facilitados por otros sitios web que tengan establecidos enlaces con destino a este Sitio Web. Por este motivo, no se hace responsable de cualquier aspecto relativo a tales sitios web.</p>
    <p><strong>III. Responsabilidad</strong></p>
    <p>ROSISTIREM, S.L. no se responsabiliza de los sitios web de terceros que sean accesibles desde este Sitio Web; ni de la exactitud, veracidad y vigencia de las informaciones que no sean de elaboración propia, cuyos contenidos pertenezcan a fuentes de información de terceros ajenos a ROSISTIREM, S.L. Pero y en base al artículo 17 de la Ley 34/2002, de 11 de julio, de servicios de la sociedad de la información y de comercio electrónico, cuando ROSISTIREM, S.L. descubra contenidos ilícitos se compromete suprimir o inutilizar estos enlaces, así como la retirada o, en su caso, bloqueo de aquellos contenidos que pudieran ser ilícitos o infringir derechos de terceros, de acuerdo con los artículos 11 y 16 de la misma Ley. Así como ROSISTIREM, S.L. no se responsabilizará de los daños y perjuicios que se produzcan por fallos o malas configuraciones del software instalado en el dispositivo del internauta. Se excluye toda responsabilidad por alguna incidencia técnica o fallo que se produzca cuando el usuario se conecte a internet. Igualmente, no se garantiza la inexistencia de interrupciones o errores en el acceso al Sitio Web y ROSISTIREM, S.L. se reserva el derecho a actualizar, modificar o eliminar la información contenida en su Sitio Web, así como su configuración o presentación, en cualquier momento sin asumir ninguna responsabilidad por ello.</p>
    <p><strong>IV. Obligaciones y responsabilidades de los usuarios</strong></p>
    <p>El usuario se compromete, mientras use este sitio web, a no incumplir la legislación vigente, la buena fe, la costumbre y el orden público. Queda prohibido el uso con fines ilícitos, engañosos, malintencionados o lesivos para ROSISTIREM o terceros. Por tanto, el uso debe ser adecuado y correcto, absteniéndose el usuario a realizar conductas dañinas a la imagen, intereses y/o derechos de ROSISTIREM y/o terceros. Así como el usuario deberá abstenerse de dañar, inutilizar o sobrecargar el Sitio Web y de acceder, utilizar y/o manipular los datos de ROSISTIREM.</p>
    <p>Por otro lado, el usuario se compromete a facilitar información veraz a través de las comunicaciones con ROSISTIREM, siendo así su único responsable de los daños o perjuicios que pudiera causar dicha información, por ser inexacta o falsa, tanto a ROSISTIREM como a terceros y el usuario es el único responsable de asegurarse de cumplir con los requisitos técnicos mínimos y de conexión a internet necesarios para el correcto uso del Sitio Web, por lo que ROSISTIREM no asumirá responsabilidad alguna por la inadecuación de los requisitos técnicos de los equipos del usuario que impidan el correcto funcionamiento operativo.</p>
    <p>ROSISTIREM aplica las medidas de seguridad razonablemente adecuadas para detectar la existencia de virus, incluso en los archivos que se puedan descargar derivados del uso del Sitio Web, pero hay que tener en cuenta que las medidas de seguridad de los sistemas informáticos no son enteramente fiables por lo que ROSISTIREM no puede garantizar la inexistencia de virus u otros elementos que pudieran incidir en los sistemas informáticos, documentos y/o ficheros del usuario. Rogamos a los usuarios que se abstengan de introducir o difundir en la red virus informáticos o sistemas físicos o lógicos que puedan provocar daños a ROSISTIREM o terceros.</p>
    <p>Por lo que ROSISTIREM se reserva el derecho a emprender las acciones legales necesarias en defensa de sus intereses o suspender temporalmente, y sin previo aviso, la accesibilidad al Sitio Web con motivo de operaciones de mantenimiento, reparación, actualización o mejora.</p>
    <p>Para ser más concretos, el usuario se compromete a utilizar este Sitio Web respetando los siguientes puntos:<br> -El usuario se compromete a no realizar ningún intento de violación de  niveles de acceso, manipulación incorrecta de datos, duplicaciones y  exportaciones de datos o informaciones protegidas por propiedad  intelectual u otros derechos legales, intentar el acceso a áreas  restringidas de los sistemas informáticos de ROSISTIREM, introducción de programas, virus o cualquier otro dispositivo que produzca o pueda  producir modificaciones en el sistema informático de ROSISTIREM o de terceros.<br> -El usuario no podrá ceder ni transmitir a un tercero el nombre de  usuario y contraseña de acceso quedando, en definitiva, prohibida la  utilización del sitio web para cualquier otro fin que no sea la exclusiva  satisfacción de sus propias necesidades de uso, o que no sea el uso  descrito en el sitio web.<br> -El usuario proveerá los medios necesarios para asegurar que las  contraseñas y claves de acceso a la aplicación permanecerán bajo su  control y no serán divulgadas, copiadas, reproducidas por parte de  terceras personas no autorizadas, debiendo custodiar las mismas por  medios físicos y lógicos. El usuario debe notificarnos de inmediato  cualquier uso no autorizado o falla de seguridad de tu cuenta o nuestros  servicios.<br> -Queda absolutamente prohibido al usuario, de forma enunciativa pero no limitativa, realizar ingeniería inversa, descompilar, desensamblar,  reproducir, traducir, modificar, versionar, comercializar, duplicar,  transformar ni transmitir a terceros, en todo o en parte el sitio web, así  como eliminar, manipular o alterar de cualquier modo cualquier aviso o  etiqueta física o lógica que incluya los derechos de propiedad de  ROSISTIREM sobre la aplicación.<br> -La utilización del sitio web no implica la aceptación, aprobación y/o  conocimiento por parte del ROSISTIREM del uso indebido que se haga  del sitio web, ya que ROSISTIREM sólo proporciona al usuario permisos  para hacer un correcto uso de la misma, conforme al presente contrato. El usuario es el único responsable del correcto uso del sitio web. Que en caso de que no cumpliera con las obligaciones aquí recogidas, ROSISTIREM podrá cesar la prestación de servicios, mediando  notificación por escrito de los motivos de dicho cese, y sin perjuicio de la penalización que pudiera corresponder.<br> -Todos los derechos que no se hayan incluido expresamente en las  presentes condiciones de uso, incluidos los derechos en materia de  propiedad intelectual e industrial, quedan reservados a ROSISTIREM.</p>
    <p><strong>V. TÉRMINOS Y CONDICIONES GENERALES DE USO</strong></p>
    <p>El objeto de las presentes Condiciones Generales de Uso (en adelante, Condiciones) es regular el acceso y la utilización del Sitio Web. A los efectos de las presentes Condiciones se entenderá como Sitio Web: la apariencia externa de los interfaces de pantalla, tanto de forma estática como de forma dinámica, es decir, el árbol de navegación; y todos los elementos integrados tanto en los interfaces de pantalla como en el árbol de navegación (en adelante, Contenidos) y todos aquellos servicios o recursos en línea que en su caso ofrezca a los Usuarios (en adelante, Servicios).</p>
    <p>ROSISTIREMse reserva la facultad de modificar, en cualquier momento, y sin aviso previo, la presentación y configuración del Sitio Web y de los Contenidos y Servicios que en él pudieran estar incorporados. El Usuario reconoce y acepta que en cualquier momentoROSISTIREMpueda interrumpir, desactivar y/o cancelar cualquiera de estos elementos que se integran en el Sitio Web o el acceso a los mismos.</p>
    <p>El acceso al Sitio Web por el Usuario tiene carácter libre y, por regla general, es gratuito sin que el Usuario tenga que proporcionar una contraprestación para poder disfrutar de ello, salvo en lo relativo al coste de conexión a través de la red de telecomunicaciones suministrada por el proveedor de acceso que hubiere contratado el Usuario.</p>
    <p>La utilización de alguno de los Contenidos o Servicios del Sitio Web podrá hacerse mediante la suscripción o registro previo del Usuario.</p>
    <p><strong>VI. Objeto del Sitio Web</strong></p>
    <p>El objeto de este Sitio Web es ofertar, promocionar y permitir la contratación online, a distancia, y entrega de todo tipo de plantas, flores y complementos a los territorios indicados abajo, tal y como se regula en los presentes Términos y Condiciones.</p>
    <p><strong>VII. Duración del contrato</strong></p>
    <p>El contrato establecido entre ROSISTIREM y el usuario tendrá una duración dependiente la entrega del producto. Para el caso en que se realicen compras periódicas mediante una suscripción a través del área “Suscripciones”, la duración queda sujeta a la solicitud de baja del servicio por parte del cliente, sin perjuicio del derecho de desistimiento.</p>
    <p><strong>VIII. Disponibilidad de los productos ofertados</strong></p>
    <p>ROSISTIREM, S.L. en cumplimiento de la normativa vigente, ofrece información sobre todos los productos y servicios ofertados, sus características y precios, en el Sitio Web. Los productos se presentan incorporando una fotografía y las características esenciales del mismo, esta es la información obtenida del propio fabricante. El color del producto, observable en la fotografía no es vinculante. En las características se identifica el mismo. Pero ROSISTIREM, S.L. se reserva el derecho a retirar, reponer o cambiar los productos y servicios sin previo aviso y en cualquier momento. De esta forma, los productos ofrecidos en cada momento se regirán por los Términos y Condiciones vigentes en cada caso.</p>
    <p>En caso de un producto en oferta, siempre se indicará en el Sitio Web el precio de oferta y su validez junto a sus características esenciales.</p>
    <p>Todos los precios son mostrados en euros e incluyen el I.V.A. aplicable y/o cualquier otro impuesto que fueran de aplicación. Dichos precios serán en todo momento los vigentes, exceptuándose los posibles errores tipográficos manifiestos. El transporte no viene incluido dentro de los precios mostrados para los productos, desglosándose su coste posteriormente en el momento de finalización de la compra a excepción que en el Sitio Web se indique lo contrario por formar parte de un periodo de oferta.</p>
    <p>El cliente puede solicitar el envío de newsletters e información actualizada de ofertas, descuentos y promociones aplicables en cada momento, así como sobre la calidad, características y origen de los productos del Sitio Web.</p>
    <p>La disponibilidad de los productos ofrecidos puede variar en función de la demanda de los clientes. Pese a que se actualiza el stock periódicamente, el producto solicitado por el cliente podría estar agotado en ese momento. En caso de no ejecución por indisponibilidad, generalmente se avisa de ello al cliente en el mismo proceso de compra, ofreciéndole la posibilidad de que ROSISTIREM, S.L. le informe mediante correo electrónico cuando vuelva a estar disponible el producto en cuestión. En todo caso, ROSISTIREM, S.L. en el momento que tenga conocimiento de tal indisponibilidad lo notificará al cliente, por medio de un correo electrónico. El periodo de esta comunicación no superará en ningún caso el plazo máximo de 30 días, a partir del día siguiente al pedido. En este caso ROSISTIREM propondrá al cliente el rembolso del dinero o un producto parecido o de superior calidad y el cliente será quien escoja la que más le convenga y en el supuesto que el abono no se realice pasados 30 días de la compra, el usuario podrá reclamar el doble de la cantidad adeudada, sin perjuicio a su derecho de ser indemnizado.</p>
    <p><strong>IX. Trámites de la contratación</strong></p>
    <p>Para la compra y contratación de los productos y servicios ofertados a través del Sitio Web es necesario crear una cuenta personal, accediendo a través de una cuenta de Facebook o bien aportando los datos requeridos conforme a nuestra Política de privacidad. Una vez se haya accedido, se confirman los productos y servicios seleccionados, los datos del destinatario y momento de entrega. Cuando el destinatario sea un tercero distinto al comprador, sólo se podrán introducir los datos personales del destinatario en los que el mismo haya dado el correspondiente consentimiento informado para que se puedan tratar los datos a los efectos de la recepción del pedido y para ROSISTIREM, S.L. pueda realizar el correspondiente seguimiento del mismo con el destinatario. El cliente/comprador responderá frente a ROSISTIREM, S.L. de la legitimación y calidad de dichos datos del destinatario. La compra se cierra con la fase de pago, previa elección del medio e introducción de los datos requeridos.</p>
    <p>Finalizado el proceso de compra el cliente recibirá una confirmación por correo electrónico y/o SMS junto con la correspondiente factura o copia del pedido. Es imprescindible que durante el proceso de compra el cliente indique un correo electrónico o número de teléfono válido. Si en 24 horas desde la finalización del pedido no recibe la confirmación, póngase en contacto con nosotros.</p>
    <p><strong>X. Entrega del pedido</strong></p>
    <p>A través del Sitio Web pueden aplicar-se sistemas de seguimiento durante todo el proceso de preparación del pedido y envío hasta su entrega, indicando el estado del pedido en cada fase y facilitar la comunicación ante cualquier imprevisto para garantizar la calidad del servicio en todo momento. En el caso que no sea posible visualizar el estado del pedido, el cliente podrá ponerse en contacto con nosotros mediante los medios de contacto facilitados anteriormente o en el e-mail <a href="mailto:rosistirem@gmail.com">rosistirem@gmail.com</a> para conocer los datos que no pueda visualizar relativos a la entrega del pedido.</p>
    <p>Se hará entrega del pedido en la dirección indicada por el cliente en el proceso de compra en el plazo aproximado de 24h a 72h laborables desde que los mismos salgan del almacén de ROSISTIREM, S.L. En el caso que la entrega del pedido no pueda completarse debido a que los datos de entrega estaban incorrectos, incompletos o falsos o cuando la entrega no se realice por causas ajenas a la empresa de envío asignada a tal efecto, o por la ausencia del destinatario o en Aduanas, ROSISTIREM, S.L. no asumirá responsabilidad alguna, pero si que se compromete a entregar en un máximo de 30 días laborales después de la contratación.<br><br>Debido a la situación excepcional del COVID-19 las fechas de entrega pueden verse afectadas en un plazo de 48-72h.</p>
    <p>El cliente asume los riesgos de deterioro, menoscabo, daños y pérdida de los productos del pedido a partir del momento de la entrega de los mismos de acuerdo al procedimiento regulado en los presentes Términos y Condiciones. El cliente será responsable del almacenaje y conservación de los productos en las condiciones que, en su caso, se establezcan en su etiquetado.</p>
    <p><strong>XI. Precios</strong></p>
    <p>Todos los productos indican el precio de venta en Euros e incluyen el Impuesto sobre el Valor Añadido (IVA). Si fuera aplicable cualquier otro impuesto, así se indicaría. Dichos precios serán en todo momento los vigentes, exceptuándose los posibles errores tipográficos manifiestos.</p>
    <p>El precio de cada producto será el que se estipule en cada momento en el Sitio Web a excepción de error manifiesto, pero los precios pueden cambiar en cualquier momento aunque los posibles cambios no afectarán a los pedidos ya confirmados.</p>
    <p><strong>XII. Gastos de envío</strong></p>
    <p>ROSISTIREM, S.L. especificará los precios de envío una vez se introduzcan los datos de entrega. Estos precios pueden fluctuar en función de la demanda del mercado y en el caso de la promoción de envíos gratuitos en España se excluirá las Islas Canarias, Ceuta y Melilla. Los gastos de envío pueden variar cuando el cliente solicite un momento de entrega determinado (p.ej. entrega urgente), en cuyo caso, la cuantía de dichos costes de envío vendrá detallada durante el proceso de compra.</p>
    <p><strong>XIII. Formas de pago y ejecución del pedido</strong></p>
    <p>El cliente podrá abonar el importe de su pedido optando por cualquiera de las siguientes formas. Durante el proceso de compra deberá indicar su elección:</p>
    <p><span style="text-decoration: underline;">Tarjeta de crédito o débito, VISA, MASTERCARD, AMERICAN</span></p>
    <p>Todas las operaciones que implican la transmisión de datos personales o bancarios se realizan utilizando un entorno seguro, un servidor basado en la tecnología de seguridad estándar SSL (Secure Sockets Layer). Toda la información que nos transmita viaja cifrada a través de la red.</p>
    <p>Asimismo, los datos sobre su tarjeta de crédito son introducidos directamente en Stripe (pasarela de pago) o Addon Payments (pasarela de pago de La Caixa) y no son introducidos ni registrados en ningún servidor de ROSISTIREM, S.L.</p>
    <p>Al pagar con tarjeta VISA o MASTERCARD o AMERICAN se le solicitarán siempre los siguientes datos: el número de tarjeta, la fecha de caducidad, y un Código de Validación que coincide con las tres últimas cifras del número impreso en cursiva en el reverso de su tarjeta VISA o MASTERCARD o AMERICAN , ofreciendo, de esta forma, más garantías acerca de la seguridad de la transacción.</p>
    <p>Cuando el importe de una compra hubiese sido cargado fraudulenta o indebidamente utilizando el número de una tarjeta de pago, su titular podrá exigir la inmediata anulación del cargo. En tal caso, las correspondientes anotaciones de adeudo y reabono en las cuentas del proveedor y del titular se efectuarán a la mayor brevedad.</p>
    <p>Sin embargo, si la compra hubiese sido efectivamente realizada por el titular de la tarjeta y la exigencia de devolución no fuera consecuencia de haberse ejercido el derecho de resolución y, por tanto, hubiese exigido indebidamente la anulación del correspondiente cargo, aquel quedará obligado frente a ROSISTIREM, S.L. al resarcimiento de los daños y perjuicios ocasionados como consecuencia de dicha anulación.</p>
    <p><span style="text-decoration: underline;">Paypal</span></p>
    <p>Permite enviar pagos en Internet de forma segura y cómoda. La red de PayPal se basa en la infraestructura financiera existente de cuentas bancarias y tarjetas de crédito para crear una solución global de pago en tiempo real. Paypal ofrece un servicio especialmente pensado para aquellos a los que no les satisfacen los mecanismos de pago tradicionales. Puede conocer más detalles en http://www.paypal.com</p>
    <p><span style="text-decoration: underline;">Amazon payments</span></p>
    <p>Amazon Payments ofrece un servicio de pago online de confianza que permite a los clientes que dispongan de una cuenta personal en Amazon efectuar pagos a usuarios con cuentas de vendedor o cuentas de empresa que utilicen servicios y aplicaciones basados en Internet o en el móvil. Puede conocer más detalles en: https://pay.amazon.es/help/201751590</p>
    <p><span style="text-decoration: underline;">Google payments</span></p>
    <p>Google Pay permite al cliente guardar sus datos de pago en su cuenta de Google, gestionarlos desde un mismo lugar y usarlos para realizar transacciones con Google y con terceros a través de tarjetas de crédito o débito, tarjetas regalo, números de cuenta bancaria o virtuales, carteras digitales, etc. Puede conocer más detalles en: https://payments.google.com/payments/apis-secure/get_legal_document?ldo=0&amp;ldt=buyertos&amp;ldr=ES.</p>
    <p>En referencia a la transmisión de datos personales que traigan causa del pago de los pedidos, consulte nuestra Política de privacidad.</p>
    <p><strong><u>XIV. Garantías</u></strong></p>
    <p>Todos los productos ofrecidos en el Sitio Web tienen la garantía comercial del proveedor del mismo. El cliente tiene a su disposición un servicio de posventa, mientras esté vigente la garantía, que podrá ejecutar dirigiéndose a ROSISTIREM SL.</p>
    <p><strong><u>XV. Derecho de desistimiento, devoluciones y reclamaciones</u></strong></p>
    <p><span style="text-decoration: underline;">Derecho de desistimiento</span></p>
    <p>Según lo establecido el artículo 103 del Real Decreto Legislativo 1/2007, de 16 de noviembre, por el que se aprueba el texto refundido de la Ley General para la Defensa de los Consumidores y Usuarios y otras leyes complementarias, los suministros de bienes confeccionado conforme a las especificaciones del consumidor o claramente personalizados, o que, por su naturaleza, no puedan ser devueltos o puedan deteriorarse o caducar con rapidez, están exentos de desistimiento.</p>
    <p>Sin perjuicio de lo anterior, sí opera el derecho de desistimiento para productos o servicios que no reúnan las características anteriores, tales como jarrones. Para estos casos, el cliente puede desistir del contrato durante los 14 días siguientes desde la entrega del pedido, sin tener que justificar motivo alguno. A consecuencia de tu desistimiento, ROSISTIREM, S.L. procederá a reembolsar el pago íntegro por los productos o servicios desistidos, incluyendo, en su caso, gastos de entrega ordinarios, antes de 14 días desde la recepción de la solicitud de desistimiento. El reembolso se realizará por el mismo medio utilizado por el cliente para el pago, salvo indicación contraria del cliente.</p>
    <p>El cliente deberá devolver los productos desistidos, asumiendo el coste de devolución, en plazo de 14 días desde comunicado el desistimiento. ROSISTIREM, S.L. podrá retener el reembolso hasta la devolución de los productos, así como disminuir la cantidad a reembolsar cuando los productos le sean devueltos en mal estado.</p>
    <p>Cuando el cliente ejerza su derecho de desistimiento sobre el servicio de suscripciones o tarjetas regalo, ROSISTIREM, S.L. retendrá los importes por valor de las compras y entregas que ya se hayan ejecutado, procediendo al reembolso del importe restante a consumir.</p>
    <p>Para ejercer el derecho de desistimiento, deberá enviarnos un e-mail indicándonos su nombre, apellido, numero de pedido, productos a desistir, un teléfono de contacto y el motivo para ejercer el derecho de desistimiento a rosistirem@gmail.com.</p>
    <p><span style="text-decoration: underline;">Devoluciones</span></p>
    <p>En caso de existir algún problema con el pedido y el cliente quiera devolver el mismo deberá enviar un e-mail a <a href="mailto:rosistirem@gmail.com">rosistirem@gmail.com</a> y ROSISTIREM, S.L. se obliga a devolver el importe íntegro del pedido o reponer el producto por otro nuevo en estos casos:<br> -Cuando el producto no haya sido entregado en la fecha acordada y dicha responsabilidad no pueda atribuirse al destinatario, se devolverá el importe.<br> -Cuando se aprecien defectos en el ramo, o este no se corresponda con las características del pedido realizado, se devolverá el importe o se restituirá el pedido por uno nuevo.<br> -Cuando se haya contratado la entrega en una franja horaria determinada, y se haya cobrado el correspondiente suplemento al efecto, se devolverá dicho importe cuando se produzcan retrasos en la entrega por causa no imputable al destinatario.<br> -En algunos envíos, puede que alguna flor del pedido no esté disponible debido a problemas de calidad o disponibilidad. En estos casos, nos reservamos el derecho de sustituir esta flor por una del mismo valor o superior.</p>
    <p><span style="text-decoration: underline;">Reclamaciones</span></p>
    <p>Si el cliente desea presentar una reclamación, puede hacerlo a través del correo electrónico <a href="mailto:rosistirem@gmail.com">rosistirem@gmail.com</a> o en la oficina de defensa al consumidor.</p>
    <p><span style="text-decoration: underline;">Disputas en línea</span></p>
    <p>No obstante, lo anterior, conforme al Reglamento (UE) 524/2013, la Comisión Europea facilita una plataforma de acceso gratuito para la resolución extrajudicial de conflictos online por la contratación electrónica (http://ec.europa.eu/consumers/odr/) al que las partes pueden someterse voluntariamente, mediante la intervención del llamado Organismo de resolución de litigios, que actúa como intermediario neutral entre ambas partes.</p>
    <p><strong><u>XVI. Obligaciones del usuario / cliente</u></strong></p>
    <p>Como usuario o cliente declara expresamente conocer, entender y aceptar las condiciones de uso y contratación bajo los presente Términos y Condiciones. Del mismo modo, declara ser mayor de 16 años de edad y tener la capacidad jurídica y de obrar necesarias para el acceso a este sitio web de ROSISTIREM, S.L. y la contratación por medio de estos.</p>
    <p>Además, el cliente se obliga: a pagar puntualmente por el servicio o servicios contratados,a realizar un buen uso del Sitio Web y respetar las leyes aplicables (incluidas, a título enunciativo pero no limitativo, las de propiedad intelectual e industrial) y los Textos legales de aplicación en el Sitio Web y, por extensión, a no infringir los derechos de terceros ni realizar ninguna actividad ilícita y a no participar en ninguna actividad que dificulte o interfiera en el funcionamiento del Servicio, incluyendo el funcionamiento de los servidores y redes que están conectados con el servicio.</p>
    <p>Acepta ser el responsable único, sin que ROSISTIREM, S.L. deba asumir responsabilidad alguna frente al cliente o terceros, de cualquier incumplimiento de sus obligaciones previstas en los Textos legales, así como de las consecuencias de dicho incumplimiento, incluyendo cualesquiera pérdidas o daños en que podamos incurrir.</p>
    <p>Ser usuario del Sitio Web implica que reconoce haber leído y aceptado los Textos legales (Aviso legal y Términos y Condiciones Generales de Uso, Política de privacidad y Política de cookies) y lo que los extienda la normativa legal aplicable en esta.</p>
    <p><strong><u>XVII. Jurisdicción</u></strong></p>
    <p>Sin perjuicio de la opción de la que disponen las partes para someterse voluntariamente al sistema de Resolución de litigios en línea mencionado en el apartado anterior, la relación entre el usuario y el prestador se regirá por la normativa vigente y de aplicación en el territorio español. De surgir cualquier controversia las partes podrán someter sus conflictos a arbitraje o acudir a la jurisdicción ordinaria cumpliendo con las normas sobre jurisdicción y competencia al respecto, con sometimiento al foro del domicilio del consumidor.</p>
    <p>En caso de que se trate de una compraventa realizada por una empresa que actúe en el marco de su actividad empresarial o comercial, ambas partes se someten, con renuncia expresa a cualquier otro fuero, a los Juzgados y Tribunales de Barcelona (España).</p>
    <p>Asimismo, ROSISTIREM, S.L. se reserva la facultad de presentar las acciones civiles y/o penales que considere oportunas por la utilización indebida del Sitio Web y sus contenidos, o por el incumplimiento de los presentes Términos &amp; Condiciones.</p>
    <p>Este documento de Aviso Legal y Condiciones Generales de uso de un sitio web ha sido creado por el departamento legal de Rosistirem el día 15/07/2020.</p>
    <p><a><u>Información de contacto de ROSISTIREM</u></a></p>
    <p>Dirección:Carrer Rull 3, 08002 Barcelona<br>Teléfono de contacto:931997199<br>Email de contacto:<a href="mailto:rosistirem@gmail.com">rosistirem@gmail.com</a><br>Actualización de Política: 15/07/2020</p>